# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-02 18:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=50)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
