# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-08 17:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eol_feedback', '0002_sectionvisibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolfeedback',
            name='block_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sectionvisibility',
            unique_together=set([('section_id', 'course_id')]),
        ),
        migrations.AlterIndexTogether(
            name='sectionvisibility',
            index_together=set([('section_id', 'course_id')]),
        ),
    ]
