name: Python application test

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'master'
      - 'main'
    paths-ignore:
      - '.github/workflows/**'
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        mkdir wf_tmp
        wget https://raw.githubusercontent.com/eol-uchile/eol_feedback/master/.github/docker-compose.yml -O wf_tmp/docker-compose.yml
        cd wf_tmp/
        docker-compose run lms /openedx/requirements/app/.github/test.sh
